### ISSUE TITLE
error: subprocess-exited-with-error, unable to install

### ISSUE THREAD

**Issue by BatmanBegins** [mikecokina/elisa#21]
Perhaps it is just me, but I am unable to get around the  error: subprocess-exited-with-error error dialog:

I've installed Python 3.8.10 via 
pyenv install 3.8.10
pyenv virtualenv 3.8.10 elisa-py38
pyenv activate elisa-py38
pip install git+https://github.com/mikecokina/elisa.git@dev

With the same error. I've cloned the repo locally and edited versions within requirements.txt to try to match versions with Python 3.10.12 compatible versions and received the same error. 

Below is a sanitized output of the error: 

_<username>@<hostname>:~/elisa$ pip install .
Processing /home/batman/elisa
  Preparing metadata (setup.py) ... done
Collecting astropy<4.4,>=4.0.1 (from elisa==0.6.dev0)
  Using cached astropy-4.3.1.tar.gz (7.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "/home/<username>/eliza/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/<username>/eliza/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/<username>/eliza/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-zua826l6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-zua826l6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-zua826l6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "/tmp/pip-build-env-zua826l6/overlay/lib/python3.10/site-packages/extension_helpers/_setup_helpers.py", line 63, in get_extensions
          for setuppkg in iter_setup_packages(srcdir, packages):
        File "/tmp/pip-build-env-zua826l6/overlay/lib/python3.10/site-packages/extension_helpers/_setup_helpers.py", line 159, in iter_setup_packages
          module = import_file(setup_package, name=packagename + ".setup_package")
        File "/tmp/pip-build-env-zua826l6/overlay/lib/python3.10/site-packages/extension_helpers/_utils.py", line 136, in import_file
          loader.exec_module(mod)
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "./astropy/modeling/setup_package.py", line 11, in <module>
          wcs_setup_package = import_file(join('astropy', 'wcs', 'setup_package.py'))
        File "/tmp/pip-build-env-zua826l6/overlay/lib/python3.10/site-packages/extension_helpers/_utils.py", line 136, in import_file
          loader.exec_module(mod)
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "astropy/wcs/setup_package.py", line 12, in <module>
          from setuptools.dep_util import newer_group
      ModuleNotFoundError: No module named 'setuptools.dep_util'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip._

Any suggestions?

**Comment by BatmanBegins** [comment]
Found that it works just fine within conda/mamba. 
The version of numpy only works on python 3.6.x-3.8.x
